LAMMPS_EXECUTABLE = "/home/federico/sistemas_complejos/lammps/lammps/build6/lmp"
LAMMPS_TOKO_EXECUTABLE = "/home/gdossantos/Lammps_Stable_Oct2020/lammps-29Oct20/src/lmp_g++_openmpi"
LAMMPS_TEMPLATE_PATH = "../lammps.template"
SLURM_TEMPLATE_PATH = "../slurm.template"
LOCAL_EXECUTION_PATH = "../executions"
